### ISSUE TITLE
I can't make a swap

### ISSUE THREAD

**Issue by alexchungcdc** [raydium-io/sdk_demo#1]
I try the dev and prod demo, I could keep getting tansaction hash without an error, but  I could't see any transaction detail through the explorer. I checked the transaction and it said "not Found", is it actually working for doing swap through raydium for this demo?

**Comment by alpha-defi** [comment]
@alexchungcdc I was able to swap successfully for both mainnet and devnet. My experience was documented at https://sdk.alphadefi.info/guides/swap if that helps.

Otherwise, for historical context within this issue, could you please elaborate on the exact steps you took to reach the "not found" error? I recall I ran into that error was well for devnet when my wallet did not have tokens available to swap.
